#
---

- name: verify_requested_users
  assert:
    that: (user | length) > 0
    quiet: true

- name: make_account
  user:
    name: '{{user}}'
    group: '{{group}}' # primary group was specified in 'accounts'
    groups: '{{suppls | ternary(suppls + [user], user)}}'
    shell: '{{shell}}'
    createhome: false

- name: make_homedir
  file:
    name: '{{homedir}}'
    state: directory
    owner: '{{user}}'
    group: '{{group}}'
    mode: '{{mode}}'
  register: r

# only do homedir skeleton if we made it and requested
- set_fact: { made_homedir: "{{(r.diff.before.state | default) == 'absent'}}" }
- set_fact: { init_homedir: '{{(skel | bool) and made_homedir}}' }
- name: do_homedir_initialization
  when: init_homedir
  block:

    - name: copy_skel_files
      include_role:
        name: skelfiles
      vars:
        skelfiles_user: '{{user}}'

    - name: set_owners_and_modes
      mk4group:
        dir: '{{homedir}}'
        user: '{{user}}'
        group: '{{group}}'

# and finally we let ansible install the key and set permissions
# specifically on the ~/.ssh directory (although, note that we do
# provision with StrictModes=no also); this must be done last after all
# permissions settings have been done
#
- name: setup_authorized_key
  when: addauth | bool
  authorized_key:
    user: '{{user}}'
    key: "{{lookup('file', authfile)}}"
    path: "{{homedir + '/.ssh/authorized_keys'}}"
    manage_dir: true
