#
# ansible-role-ubunode
#   do basics that every ubuntu node gets after provisioning
#
# desc:
#   - timezone, locale, reserved uids/gids, sudoers, pams, umask, noskel
#
# may:
#   - ubunode_timezone
#   - ubunode_locale
#   - ubumode_umask
#   - ubunode_comment_files
#   - ubunode_comment_substrs
#
---

- name: display_phase
  debug:
    var: phase

- name: implement_ssh_changes
  block:

    # TODO: we should maybe be a leaf role and not call other roles?
    - name: write_custom_ssh_configs
      include_role:
        name: ssh

    # have to reload ssh config prior to doing socket activation changes
    # or we get quirks like systemd-orphaned procs on u24+ and restart
    # fails, seems that only a reboot actually fixes it so we defer that
    #
    - name: perform_queued_ssh_reload
      meta: flush_handlers

- name: run_by_phase
  # todo: not sure why we need the full path, it doesn't seem to take
  # relative, not sure why
  include_tasks: "{{role_path}}/tasks/{{phase | d('operate')}}.yml"
