#
---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudcore
  namespace: kubeedge
spec:
  interval: 24h
  chart:
    spec:
      chart: manifests/charts/cloudcore
      sourceRef:
        kind: GitRepository
        name: kubeedge
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    mosquitto:
      enable: false
    cloudCore:
      modules:
        cloudHub:
          advertiseAddress:
            - ${KUBEEDGE_LBIP} # plex-internal address we NAT from
            - ${KUBEEDGE_LANIP}  # plumb as eth0 on laptop dongle
          websocket:
            enable: true
            port: 10000
    service:
      enabled: false
