#
---

- name: copy_remote_syslog_configs
  copy:
    src: '{{rcfile}}'
    dest: "{{
      '/etc/rsyslog.d/' + (
        rcfile | basename | regex_replace(
          '^(\\d\\d-)', '\\1' + setup_prefix + '-'
    ))}}"
  loop_control:
    loop_var: rcfile
  with_fileglob: 'files/*'
  notify: rsyslog_handler_reload

# we placed this here during cloudinit to make sure /var/log/messages has all
# messages written to it, but we'll replace that file with one from here that
# doesn't call fdatasync(2)
#
- name: remove_bootstrap_syslogging
  file:
    path: /etc/rsyslog.d/20-cloud-config.conf
    state: absent
  notify: rsyslog_handler_reload

# we write this file ourselves, but redhat duplicates it (not inf ull)
- name: disable_system_messages_writes
  replace:
    regexp: '^(\s*[^#].*/var/log/messages\s*)$'
    replace: '# (ansible-disabled): \1'
    dest: /etc/rsyslog.conf
  when: (ansible_distribution | lower) == 'centos'
  notify: rsyslog_handler_reload
