#
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-decrypted
    namespace: flux-system
type: Opaque
stringData: {}
sops:
    encrypted_regex: ^stringData$
    lastmodified: "2026-06-27T04:22:13Z"
    mac: ENC[AES256_GCM,data:7AqVORuLujpOM8ZwkmE7EAAqXlkGvQRsyJztdVWDcuBBRgchNaBrR9qJ3bpzZosRY333AukvGPv5rflvhciZ/Hrd+C5lBCfAjmXsWYuEpSd/qkieQ8rbF1na8hqi/31SeWY5pdsheGziwZKdQA1vo3sq/o9YQC5d4PGrpXcdg04=,iv:5sd7Xbpr7eaceGNRzudXivVe4r4NKMxjSN5lTMlHDbM=,tag:URyWk9ZQdJEJAwijK+BRZQ==,type:str]
    pgp:
        - created_at: "2026-06-27T02:15:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0sq29FQzV6dAQ//efjpInwoOZ3w1G/q8J/gYWl7DHxl278cCsnoqJO/wvAa
            iTTJjIlVL2KKSUDw9RFgr34pgMfU6qWh93vDAe6f+hSSVjzc+S3aBOHg/32AACdV
            Aqs1z91rAAoNhMP/Zy7eSwIUBxXuq1GImVHq0CEL2/8G8yIlD23S63HA1Z7skzaR
            SSiA+qr8VUbooVgHIYzVP7Lz4ycPMlg7nvVa9FTXBrlXOa9MhqeLG2ogZRxh70Nv
            Aq6jKBSZeidUSc2hchz0I4ZRncjhO/DJQcjpjmtxvGqiMueqhrhYtt0kTM+Qzzho
            sKQYxUdjtbydQZBR6nuDqvRwExnexk2GiCni7zkkC/TUnydH42mHBJSqnIZrhu9j
            hq+HW8eKiYFIN9FN9ktsEF+Xwm9xe4sPZtPK1zBWAJ5owaoA8ld0Cg7IS5Hft+k0
            1n10+zaZBA0UfOWU89KeqeVP/npTSjn054EEX42pgarax5p8tTlfPHnGG8RW3V/x
            xWKF94DSIvZv6DcvHzVS8DQtosYKOFsEMwaQArVNNr2VmtkrzXChkHYIEfeowArO
            YqBByRJUYIUHauukXeS3tnyIXQw2h1ySmk1ZeHtH/6XiExX4IscO6ouFfdmyRovf
            vhBIWGh5cI1ZOHdxaWTSJShCFudFvMeV2CPbX8XM/SXqyc7WbWhkxOYcHdfPHanU
            ZgEJAhCGL17lL0NrrMLC9X2NkJa9GCI4UhLu6oBrS60HCbGC1k1wwwhvRWkvIhMl
            X3UlYL9Eay5Qff8dxxCFwJmAug5iU2MjBrhB3THKAMhZGFNDLBLlNCxGsFL0fK/3
            3IfE2x9dEQ==
            =p9ib
            -----END PGP MESSAGE-----
          fp: 4B2ADBD150CD5E9D
    version: 3.13.1
