#
# fluxstrap
#   once a cluster has slaves, bootstrap flux from ~setup/clusters/<plexname>
#
# desc:
#   - runs from module.kubeslaves[<plexhost>].terraform_data.ready provisioner
#   - provisioner runs only when at least two worker nodes (data plane ready)
#   - does kubectl apply flux install manifests (gotk-components.yaml)
#   - configures git repo polling for workload manifests (gotk-sync.yaml)
#   - entirely local actions: 'nodename' used only to get plex (vars/kube.yml)

- name: prepare_flux
  hosts: '{{nodename}}'
  vars_files:
    - vars/networks.yml
    - vars/pysetup.yml
    - vars/kube.yml
    - vars/main.yml
  tasks:

    - name: bootstrap_fluxcd
      delegate_to: localhost
      vars:
        ansible_python_interpreter: "{{py3bin_setup}}"
      block:

        - name: check_installed_sops_version
          shell:
            cmd: >
              [[ "$(type -p sops)" ]]
              && : $(sops --version |& head -1 | awk '{print $2}')
              && echo $_
            executable: /bin/bash
          register: r
          failed_when: (r.rc != 0) or (r.stdout.strip() != version_sops)
          changed_when: false

        - name: check_installed_flux_version
          shell:
            cmd: '[[ "$(type -p flux)" ]] && : $(flux --version) && echo $_'
            executable: /bin/bash
          register: r
          failed_when: (r.rc != 0) or (r.stdout.strip() != version_flux)
          changed_when: false

        # flux secret needs to pre-exist flux, but must be in flux-system
        - name: precreate_flux_namespace
          kubernetes.core.k8s:
            kubeconfig: '{{kubeconfig}}'
            definition:
              - apiVersion: v1
                kind: Namespace
                metadata:
                  name: flux-system

        # todo: pass an arg that runs this and stashes keys anew rather than
        # echos the keydir.  maybe we don't need to stash it in git at all,
        # just make each one essentially random at cluster create-time.  until
        # we do that, in the meantime, we put the private key in crypt/ with
        # symlink, and pubkey in keys/, so each iteration of the clusters will
        # have the same key.  but here is how to do it:
        #
        - name: todo_reinstantiate_sops
          when: false  # todo
          shell:
            cmd: >
              :
              && homedir=`mktemp -d`
              && email=sops@omniplex.smemsh.net
              && fpropts="--list-options show-only-fpr-mbox --list-keys"
              && gcmd () { gpg --quiet --homedir=$homedir "$@"; }
              && gsfpr () { gcmd $fpropts $email "$@" | awk '{print $1}'; }
              && gsops () { gcmd --batch --passphrase '' $1 $(gsfpr) ${@:2}; }
              && gsops --quick-generate-key $email rsa4096 default never
              && gsops --quick-add-key rsa4096 encrypt never
              && gcmd --export --armor > $homedir/sops-public.asc
              && gcmd --export-secret-keys --armor > $homedir/sops-private.asc
              && tmpdir=`mktemp -d`
              && mv $homedir/sops-* $tmpdir/
              && rm -rf $homedir
              && echo $tmpdir
            executable: /bin/bash

        - name: bootstrap_flux_sops_secret
          kubernetes.core.k8s:
            kubeconfig: '{{kubeconfig}}'
            definition:
              - apiVersion: v1
                kind: Secret
                metadata:
                  name: sops-gpg
                  namespace: flux-system
                type: Opaque
                stringData:
                  sops.asc: "{{
                    lookup(
                      'file',
                      '%s/keys/kube/sops@%s.%s-private.asc' % (
                        playbook_dir, plexname, domain))}}"

        # this will generate with whatever version 'flux' binary is
        # installed in PATH (we gated the version value earlier).
        #
        - name: get_flux_install_components_yaml
          command: flux install --export
          register: r
          failed_when: r.rc != 0
          changed_when: false

        # gotk-components.yaml
        - name: kubectl_apply_flux_components
          kubernetes.core.k8s:
            definition: '{{r.stdout | from_yaml_all}}'
            kubeconfig: '{{kubeconfig}}'

        # gotk-sync.yaml
        - name: kubectl_apply_flux_sync
          kubernetes.core.k8s:
            kubeconfig: '{{kubeconfig}}'
            definition:

              - apiVersion: source.toolkit.fluxcd.io/v1
                kind: GitRepository
                metadata:
                  name: flux-system
                  namespace: flux-system
                spec:
                  # we only want to trigger reconciliation manually.  while
                  # unsuspend triggers reconciliation, it's async, and thus
                  # returns right away.  we would need unsuspend, reconcile,
                  # suspend each time.  if instead we use an extreme timeout,
                  # reconcile alone is both sufficient and synchronous.
                  #
                  suspend: false
                  interval: 86400h
                  url: https://github.com/{{setup_prefix}}/{{setup_reponame}}
                  ref:
                    branch: '{{flux_branch}}'

              - apiVersion: kustomize.toolkit.fluxcd.io/v1
                kind: Kustomization
                metadata:
                  name: flux-system
                  namespace: flux-system
                spec:
                  # for drift only; GitRepository change already triggers
                  suspend: false
                  interval: 86400h
                  prune: true
                  path: ./clusters/{{plexname}}
                  sourceRef:
                    kind: GitRepository
                    name: flux-system
