#
---

# defaults for new users if nothing was provided by either
# role invocation parameters, or the accounts: variable
#
accts_skel:     true
accts_addauth:  true
accts_base:     /home
accts_shell:    /bin/bash
accts_mode:     '02775' # keep as string to avoid bugs
accts_skel:     false

# if true, only subset of users in $sysadmin_group will be setup
accts_sysadmin_only: false

# canonical list of shell accounts
#
# todo: we should have an old-accounts and move them there,
#   with state=absent, this way the role could be run to add
#   or remove users, right now remove is not implemented
#
accounts:

  - group: sysadmin
    suppl: [dev]
    users:
      - scott

  #- group: dev
  #  users:
  #    - testuser1
