#
---

boot_serial: 0
boot_timeout: 3
boot_distro_name: '{{sysadmin_username}}@{{sysadmin_domain}}'

# let the user stop filesystem changes from being made, for
# example to run the role on an already-provisioned node
#
# TODO disabling these for now because the base image changed, labeling
# is wrong and partition is wrong but we'll leave these in and let it
# just be skipped for now, by setting these 'true'
#
boot_skip_relabel: true
boot_skip_fstab: true

# todo: pti=off is only one of many mitigations, so this is quite
# incomplete on distro versions before u20
#
boot_kernel_mitigations: "{{
  (((ansible_distribution | lower) == 'ubuntu') and
    ((ansible_distribution_major_version | int) >= 20)) | ternary(
      'mitigations=off', 'pti=off'
)}}"

boot_grub_cmdline:
  biosdevname=0
  net.ifnames=0
  usbcore.autosuspend=-1
  ipv6.disable=1
  selinux=0
  apparmor=0
  console=tty0
  console=ttyS{{boot_serial}},115200n8
  {{boot_kernel_mitigations}}
  scsi_mod.use_blk_mq=Y
  log_buf_len=8M

boot_grub_serial:
  serial
    --unit={{boot_serial}}
    --speed=115200
    --word=8
    --parity=no
    --stop=1
