#
# initssh.yml
#   copy authorized key to the system for the user
#
# desc:
#   - create ssh dir with right perms if dne
#   - ensure ssh key in authorized_keys (leave others alone)
#   - uses contents of "files/<email>-id_rsa.pub"
#
---

- name: verify_ssh_user_supplied
  assert:
    that: initssh_user is defined
    quiet: true

- name: do_ssh_authkey
  authorized_key:
    user: '{{initssh_user}}'
    key: '{{item}}'
    manage_dir: true
  with_file:
    - 'keys/ssh/{{initssh_keyid}}-id_rsa.pub'
  when: initssh_keyid is defined
  no_log: true
