#
# initssh.yml
#   copy authorized key to the system for the user
#
# desc:
#   - create ssh dir with right perms if dne
#   - ensure ssh key in authorized_keys (leave others alone)
#   - uses contents of "files/<email>-id_rsa.pub"
#
---

- assert: { that: 'mkuser_user is defined' }

- name: do_ssh_authkey
  authorized_key:
    user: '{{mkuser_user}}'
    key: '{{item}}'
    manage_dir: true
  with_file:
    - 'files/{{initssh_keyid}}-id_rsa.pub'
  when: initssh_keyid is defined
