#
# gits.yml
#    git check out and verify signature on tags
#
# scott@smemsh.net
# https://github.com/smemsh/utilsh/ (installx.sh)
# https://spdx.org/licenses/GPL-2.0
#
---


- name: repo_checkouts
  git:
    repo: 'https://github.com/{{skel_github}}/{{item.key}}'
    version: '{{item.value}}'
    recursive: false
    verify_commit: true
    dest: |-
      {%- if item.key in skel_repos_rcall -%}
      {%-     set destdir = skel_rcfiles_dir -%}
      {%- elif item.key in skel_repos_exall -%}
      {%-     set destdir = skel_srcx_dir -%}
      {%- else -%}
      {%-     set destdir = undef() -%}
      {%- endif -%}
      {{destdir}}/{{item.key}}
  with_dict: '{{skel_repos_all}}'
