#
# gits.yml
#   git checkout latest or specified versions (see defaults) and verify tags
#
---

- name: generate_cache_id
  set_fact:
    playid: '{{ansible_date_time.epoch | string}}'
  delegate_to: localhost
  run_once: true

- name: do_ghreltags_lookups
  set_fact:
    skel_repos_all: '{{
      skel_repos_all
      | ghreltags(skel_github, skel_tagprefix, playid, skel_apitok)
    }}'
  delegate_to: localhost
  throttle: 1 # essential for filter to benefit from cached prior api calls

- name: repo_checkouts
  git:
    repo: 'https://github.com/{{skel_github}}/{{item.key}}'
    version: '{{item.value}}'
    recursive: false
    verify_commit: true
    dest: |-
      {%- if item.key in skel_repos_rcall -%}
      {%-     set destdir = skel_rcfiles_dir -%}
      {%- elif item.key in skel_repos_exall -%}
      {%-     set destdir = skel_srcx_dir -%}
      {%- else -%}
      {%-     set destdir = undef() -%}
      {%- endif -%}
      {{destdir}}/{{item.key}}
  with_dict: '{{skel_repos_all}}'
