#
# installx.yml
#   runs installx and/or installrc from https://github.com/smemsh/installx/
#
# desc:
#   - runs installrc on those from skel_repos_rcfiles
#   - runs installx on those from skel_repos_exes
#
# todo:
#   - this depends on their path, but they could be installed in bin
#   - installx should be made importable as ansible module
#
---

- name: do_installx
  shell: '{{skel_srcx_dir}}/installx/installx -qf'
  args:
    chdir: '{{skel_srcx_dir}}/{{item.key}}'
  with_dict: '{{skel_repos_exes}}'

# installrc requires 'ln --relative'
# (not present in u12 coreutils)
#
- name: ensure_atleast_ubuntu14
  when: ansible_distribution == ('ubuntu' | lower())
  assert:
    that: ansible_distribution_major_version > 12
    msg: "ubuntu < 14 'ln' does not have '--relative', needed by 'installrc'"

- name: do_installrc
  shell: '{{skel_srcx_dir}}/installx/installrc -qf'
  args:
    chdir: '{{skel_rcfiles_dir}}/{{item.key}}'
  with_dict: '{{skel_repos_rcfiles}}'
