#
# installx.yml
#   runs installx and/or installrc from https://github.com/smemsh/installx/
#
# desc:
#   - runs installrc on those from skel_repos_rcfiles
#   - runs installx on those from skel_repos_exes
#
# todo:
#   - this depends on their path, but they could be installed in bin
#   - installx should be made importable as ansible module
#
---

- name: do_installx
  shell: '{{skel_srcx_dir}}/installx/installx -sqf'
  args:
    chdir: '{{skel_srcx_dir}}/{{item}}'
  with_items: '{{skel_repos_exes | list}}'
  register: r
  changed_when: r.rc == 1
  failed_when: r.rc > 1

- name: do_installrc
  shell: '{{skel_srcx_dir}}/installx/installrc -sqf'
  args:
    chdir: '{{skel_rcfiles_dir}}/{{item}}'
  with_items: '{{skel_repos_rcfiles | list}}'
  register: r
  changed_when: r.rc == 1
  failed_when: r.rc > 1
