#
---

- name: get_account_entry
  getent:
    key: '{{skelfiles_user}}'
    database: passwd
    fail_key: true

- name: determine_home_directory
  set_fact:
    homedir: '{{getent_passwd[skelfiles_user].4}}'

- name: copy_skel_files
  copy:
    src: files/
    dest: "{{homedir}}/"
    local_follow: false
  become: true
  become_user: '{{skelfiles_user}}'
