#
---

- name: fetch_existing_sysadmin_group_info
  getent:
    key: '{{sysadmin_name}}'
    database: group
    fail_key: false

- name: test_existing_group_matches_gid
  assert:
    that:
      - getent_group[sysadmin_name][1] == (sysadmin_gid | string)
    fail_msg: "group exists and does not match requested gid, aborting..."
    success_msg: "group exists and matches requested gid, skipping..."
  when: getent_group[sysadmin_name]

- name: create_sysadmin_group
  group:
    gid: '{{sysadmin_gid}}'
    name: '{{sysadmin_name}}'
    state: present
  when: not getent_group[sysadmin_name]

- name: verify_sudoers_dir_include
  lineinfile:
    name: /etc/sudoers
    line: '@includedir {{sudoers_dir}}'
  check_mode: true
  register: r
  failed_when: (r is changed) or (r is failed)

- name: verify_sudoers_dir_exists
  stat:
    path: '{{sudoers_dir}}'
  register: r
  failed_when: not r.stat.exists

- name: add_sudoers_files
  template:
    src: '{{item}}'
    dest: '{{sudoers_dir}}/{{item | basename() | splitext() | first()}}'
    owner: root
    group: root
    mode: 0400
  with_fileglob:
    - 'templates/??-sudoers-*.j2'
