#
# wraps the authkey and optionally password set
# so far this role is used by rootauth and cfgnode 20181218
#
---

- name: setup_authkeys
  when: (auth_username is defined) and (auth_users is defined)
  authorized_key:
    user: '{{auth_username}}'
    key: "{{lookup('file', auth_keydir + '/' + item + '-id_rsa.pub')}}"
    manage_dir: true
  with_items: '{{auth_users}}'

- name: set_password
  when: auth_password is defined
  user:
    name: '{{auth_username}}'
    password: '{{auth_password | password_hash}}'
    update_password: always
