#
apiVersion: v1
kind: Secret
metadata:
    name: kubeedge-secrets
    namespace: flux-system
type: Opaque
stringData:
    KUBEEDGE_TAG: ENC[AES256_GCM,data:8VqUTlmrfw==,iv:NOEkaMmZNYCmZQ4tZcBwVmSe5pP0V8KpnqeLMYhWopY=,tag:aFMqce35kDMlokL8c7kUZw==,type:str]
    KUBEEDGE_LBIP: ENC[AES256_GCM,data:fEBPEoLbCWklJKws,iv:cL9gWlKMPw9vF3T2YRakn57G5eaXNbPoKdKseqJHKIE=,tag:8WzlgpC88wHX2acowrHOuw==,type:str]
    KUBEEDGE_LANIP: ENC[AES256_GCM,data:ogg2pi7yxOlAtg==,iv:d0hinbIpMUXZ7Xc7vKwFxO1KR5CxVbBMjIxwcgK2gC4=,tag:8FbKLe2pMa9W82SD0TLspw==,type:str]
sops:
    encrypted_regex: ^stringData$
    lastmodified: "2026-06-27T06:15:50Z"
    mac: ENC[AES256_GCM,data:vIDTKJKYjSUnasqNRpOtpxMHVZMBfHlQcS/OTH1OxpnKK0SM7ECyeP/7+Y6NYNiua1mFgeK13fjyBkhrHL/gYPIkiaGA8b6pxaQL0fpKiFvlZ+vHUJXRn00BFXMJ9idMtAlMUS3lRCNdYznZWmxl1IavjzVrZDO+OKm3fCA8K4w=,iv:29ac37fxDaP+97C3Y8IU8MmRQi6gK5r1b5rElmh2EGc=,tag:ttmuHSFuzQ3KnS5F2zoN2w==,type:str]
    pgp:
        - created_at: "2026-06-27T06:15:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0sq29FQzV6dAQ//VOPYSMpEecSSkgY7Kh67nVle//IZeUHmYNLCQ0CTRjeB
            URBtnheRVS71gTDaE3HaGFGCPhK3HoYDzJTHY/VVsXcI831gVSnaXYGRxETy6jWq
            EZNH/6kTNGwmESYhF3SGtTt6M0qnxhlR5JT0iVymNdXyiPs8RG+gXKhqqzJ6s264
            dGkttbwmvV3LrHFmPQ4Jxlc9ct4N5b3xyzZTBRqkhkU6aR7P3C5NwSp+BL/6ABq5
            aqHu2R2n6VNM8UTc7kKDIGR1ZC02Ro/amA2akXbkAy3iofADhfAmHri13z0kfUy0
            TtShOPaUtlPIRUglu0Wizrj/PVcBXcEYnp2VAMAM4hhJ9UrITKjNl8CFOoWZDulf
            a9aeQl68rIuI7jIp2Vz90vQVo8jCXBn3UvjQLXeJ1tWoanGOqrztWpc4v/NJxTkf
            gGp0l4Gbjmv4aIE9SZzqM6Vxfk8JNGvpE1k+8yHF9BXaUR7W09yqp5PvT1cxJam7
            dSDEoEtdmYzqzPWCakzfdz/W+jRVmrQOSByPw4KL4XKLVf8vSK4kY+ejX3VKJiDi
            7IuUDSBX43zgn0BnQamwipSEoQCN2hNajOmr7HpRczu2L2tHcUcsVKaIUHEc1yDk
            xU1Ve/MXPR6sX7yW5lGhIUZVP98Zia/ZYvQjD2VbDmvi/eKunuhkZQuTJqd39HvU
            aAEJAhDsxq9hCkIZsawfS3tMJCOl6lnOdv7ceStKMygrMJiBVN29pBLXV938DYP9
            B1kqTIAFJPXrMOOBVBtjbuD3ZLx6W2OhIEKf1QAObznPyjqG9DF3VKWEl8kEaOuq
            X01YiGS9AxXj
            =osrw
            -----END PGP MESSAGE-----
          fp: 4B2ADBD150CD5E9D
    version: 3.13.1
