#
apiVersion: v1
kind: Secret
metadata:
    name: lb-secrets
    namespace: flux-system
type: Opaque
stringData:
    LBPOOL: ENC[AES256_GCM,data:XCKVAPeOREJ+ozk5Xy7y,iv:bESK3WnOQ0jVOu5VXpYIPYiHVWhQifP8sG+f+Y717NM=,tag:n/ToB0wCW18SqifOnjYFzw==,type:str]
sops:
    encrypted_regex: ^stringData$
    lastmodified: "2026-06-27T06:11:42Z"
    mac: ENC[AES256_GCM,data:1LCrmSfPluOPt26RB0Nghuqv0x6QbpZ7YVq48nwcfGD8nMyONcLRvNhrKMdL68yU/w5Jq+xNuxdksB+PXMSpIzXhjDFsnWPxllCgFmB7uERiCmtB/g9Voh1RRe9/3AiLkoMKw5CyrF/R5N0qJz0mJHz6dTv5HibQihiBIKLU1bw=,iv:+EJH/oP67CkUfbn+cljqi3LSPiGUqJD2CeeSnu952q0=,tag:sjbBzZPYhCbHHaq/nzTxAQ==,type:str]
    pgp:
        - created_at: "2026-06-27T06:11:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0sq29FQzV6dAQ/9FKWNJkChIrXfgKyOJPVWu4te10RBd1wHjNsCwLBbHIVT
            mpCIeiBpX6kEj66WHLETaDXIxhuRi6i8NuklripUjMUSLJUjPYIaYQZI0z2np6s9
            H/61kh/sGdvg6qW6M8SpV06dsQuSkOIz/m2U2ZjTlP1b7SQ45Os/tD5gg7HIi8pn
            Zx08cRVffxsg8zCg9tgmYLzR4scKp2wKQUXS0iAe6f8+cR9aYbn5f2UnhMdhD/fb
            76IaGGN47Lo+5e9g3PuAq1IEQCPpNgMbJPDtSJGoWGttHuHZZ2PsV0JIpcqnTfmE
            20BezAgCFqSbAFXzMlE/Vmhp5Um6spYvDwjJRi6IK2IzSdumKM5rW2+9MlDjHTG7
            RbM4NZA1sYWJ3X3WmQxIxvf4pFthuCKab/Vu38cq7JcWdYF5DO7QkcseqVV3f+AO
            TTL1UHrX0BAOXK/rxVjulDt4ngymYDSL8pUgJ0lbPYqweSObOP/5bhWBXGq6nJZn
            njza9zSmSJS7WFYDFv1nAwT2cPTtJrlRYUcrBKEsx8nlpvL5KWaM/bjAyTqZrszO
            bNpzpVX7UV5fp9LkfUM+EZES2Yl8G3w1OSDEVHYffK4lJeU80KHtxEFmf71UUY87
            GatVyqicG9kXvoPbJ/EqgPKWv8Cr/p+7ZEJ+sL8RNWeOWxOKsySA+uuMdfOIJMPU
            aAEJAhCcyJofrZxsdaOMEF3kCtyj6wHqj8I3gSYEiUjSA0Wz1t9EQqkL/zXyWNHu
            gZiGqvk5rXJTBDYTv3NV42UrS1oTClDJBHVHNEE80+JI2oXcCKnUWby2lR4nObiP
            IB274jlGZu1M
            =f680
            -----END PGP MESSAGE-----
          fp: 4B2ADBD150CD5E9D
    version: 3.13.1
