#
---

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubeedge
  namespace: flux-system
spec:
  interval: 86400h
  timeout: 5m
  url: https://github.com/kubeedge/kubeedge
  ref:
    tag: ${KUBEEDGE_TAG}
