#
---

# TODO: look at "ansible-doc -t vars host_group_vars", it may be
# possible to set "stage = all" in rcfile section [vars_host_group_vars]
# and these will get instantiated without having to add_host? because
# the default looks to be "demand" (from the source) which presumably is
# the same as "task" and thus relies on having some task run that uses
# it, before it's instantiated? just a guess, but worth trying.  will
# help iptables role as well, possibly others
#
- name: populate_hostvars_for_expansion
  add_host:
    name: '{{vm_name}}'

- name: render_cloud_init_configs_to_yaml
  set_fact:
    cloudinits_rendered: '{{lookup("template", item)}}'
  loop_control:
    # _ansible_item_label in json output for tfcloudinit
    label: '{{item | basename | splitext | first}}'
  with_fileglob: tmpl/*.j2

#  template:
#    src: tmpl/{{item}}.j2
#    dest: '{{cloudinit_destdir}}/{{item}}'
